Fix version check in check_version.yml

diff --git a/.github/workflows/check_version.yml b/.github/workflows/check_version.yml
--- a/.github/workflows/check_version.yml
+++ b/.github/workflows/check_version.yml
@@ -39,8 +39,7 @@ jobs:
         id: compare_versions
         run: |
           if [ "${{ steps.package-version-prev.outputs.current-version }}" == "${{ steps.package-version.outputs.current-version }}" ]; then
-            echo "::error::Version has not been increased, action cancelled..."
-            exit 1
+            echo "::error::Version has not been increased, action cancelled..." && exit 1
           fi
 
   check_if_release_exists:
